[package]
name = "parking_system"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
chrono = "0.4.41"
error_mapper = "0.3.11"
mysql_async = { version = "0.36.1", features = ["chrono"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }