[package]
name = "parking_system"
version = "0.1.0"
edition = "2024"

[dependencies]
error_mapper = "0.3.11"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
mysql_async = "0.36.1"
serde_json = "1.0.140"